### ISSUE TITLE
Write a function in any programming language to solve the below problem 3SUM

### ISSUE THREAD

**Issue by saptarshisarkar20** [saptarshisarkar20/Hacktoberfest2022#2]
#### Fork the repo

**Location**
Go to folder Pull Here/LeetCode/3SUM

**File name**
Take your GitHub username id like "hrithik339", "hacker-boy", etc or anything which you have.
Then add a programming language extension after this (link for C++ add .cpp and for python add.py)
Only files with the correct file name will be accepted

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
### Problem Statement

Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.

Notice that the solution set must not contain duplicate triplets.

 

 **Example 1:**

```
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
```
Explanation: 
nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.
nums[1] + nums[2] + nums[4] = 0 + 1 + (-1) = 0.
nums[0] + nums[3] + nums[4] = (-1) + 2 + (-1) = 0.
The distinct triplets are [-1,0,1] and [-1,-1,2].
Notice that the order of the output and the order of the triplets does not matter.

**Example 2:**

```
Input: nums = [0,1,1]
Output: []
```
Explanation: The only possible triplet does not sum up to 0.

**Example 3:**

```
Input: nums = [0,0,0]
Output: [[0,0,0]]
```
Explanation: The only possible triplet sums up to 0.
 

_Constraints:_

- 3 <= nums.length <= 3000
- -105 <= nums[i] <= 105

### Complete the following function

```
class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        
    }
};
```

**Comment by manng2** [comment]
Please assign to me for Hacktoberfest 2022

**Comment by saptarshisarkar20** [comment]
> Please assign to me for Hacktoberfest 2022

Don't wait to assign just work on it

**Comment by manng2** [comment]
I solved this issue by JavaScript, please review it https://github.com/saptarshisarkar20/Hacktoberfest2022/pull/32

**Comment by Karmakarsaurab** [comment]
please assign this to me ,i want to contribute in it for hacktoberfest
