### ISSUE TITLE
Write a function in any programming language to solve the below problem Palindrome Number

### ISSUE THREAD

**Issue by saptarshisarkar20** [saptarshisarkar20/Hacktoberfest2022#5]
#### Fork the repo

**Location**
Go to folder Pull Here/LeetCode/PalindromeNumber

**File name**
Take your GitHub username id like "hrithik339", "hacker-boy", etc or anything which you have.
Then add a programming language extension after this (link for C++ add .cpp and for python add.py)
Only files with the correct file name will be accepted

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
### Problem Statement

Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.
 

**Example 1:**

```
Input: x = 121
Output: true
```
Explanation: 121 reads as 121 from left to right and from right to left.

**Example** 2:

```
Input: x = -121
Output: false
```
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.

**Example 3:**
```

Input: x = 10
Output: false
```
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
 

**Constraints:**

-231 <= x <= 231 - 1
 

Follow up: Could you solve it without converting the integer to a string?

### Function

```
class Solution {
public:
    bool isPalindrome(int x) {
        
    }
};
```

**Comment by gaut2003** [comment]
Please assign this to me.

**Comment by saptarshisarkar20** [comment]
> Please assign this to me.

Don't wait to assign just work on it

**Comment by sayak01** [comment]
i am working on it

**Comment by rk-1620** [comment]
@saptarshisarkar20 I would like to work on this issue. Please assign it to me.

**Comment by neeraj3199** [comment]
i already done it please assign it to me

**Comment by manng2** [comment]
I already done it with JavaScript, please review it https://github.com/saptarshisarkar20/Hacktoberfest2022/pull/33

**Comment by Debarpan08** [comment]
Please assign this to me

**Comment by jayprakash6547** [comment]
Hi please assign this to me

**Comment by sahiljarngal** [comment]
Please @saptarshisarkar20 assign to me.

**Comment by croquis** [comment]
I would like to contribute to this issue with proper comments and logic. Kindly assign this to me.

**Comment by Debarpan08** [comment]
!assign

**Comment by saptarshisarkar20** [comment]
Don't wait to assign the issue. Start working on it and make a pull request ASAP.

**Comment by Debarpan08** [comment]
Sir,could you let me know which programming language has not been done yet
for the same question so that I can contribute?

**Comment by Debarpan08** [comment]
Sir,I have solved the problem in java.Kindly check,thanks!

**Comment by imNilabja** [comment]
I would like to do this task,can you assign me.
